sudo: required
services:
    - docker
before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
    - make test
deploy:
    provider: script
    script: make deploy
    on:
        branch: master