sudo: required
services:
    - docker
env:
    global:
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project mutant-services
    - gcloud config set compute/zone southamerica-east1-b
    - gcloud container clusters get-credentials mutant-services-cluster-south-ame-east
script:
    - make test
deploy:
    provider: script
    script: make deploy
    on:
        branch: master