apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # Allow only public actions access
    nginx.ingress.kubernetes.io/rewrite-target: /public/$1
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - mutant.services
        - www.mutant.services
      secretName: mutant.services
  rules:
    - host: mutant.services
      http:
        paths:
          - path: /mds/?(.*)
            backend:
              serviceName: mutant-determination-service-cluster-ip-service
              servicePort: 8080
          - path: /mss/?(.*)
            backend:
              serviceName: mutant-statistics-service-cluster-ip-service
              servicePort: 8080
    - host: www.mutant.services
      http:
        paths:
          - path: /mds/?(.*)
            backend:
              serviceName: mutant-determination-service-cluster-ip-service
              servicePort: 8080
          - path: /mss/?(.*)
            backend:
              serviceName: mutant-statistics-service-cluster-ip-service
              servicePort: 8080