apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutant-statistics-service
spec:
  replicas: 5
  selector:
    matchLabels:
      component: mss
  template:
    metadata:
      labels:
        component: mss
    spec:
      containers:
        - name: mss
          image: lautaronavarro/mutant-statistics-service
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redispassword
                  key: REDISPASSWORD