apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutant-determination-service
spec:
  replicas: 5
  selector:
    matchLabels:
      component: mds
  template:
    metadata:
      labels:
        component: mds
    spec:
      containers:
        - name: mds
          image: lautaronavarro/mutant-determination-service
          ports:
            - containerPort: 8080
          env:
            - name: MONGOUSER
              value: admin
            - name: MONGOHOST
              value: mongo-cluster-ip-service
            - name: MONGODATABASE
              value: determination_service
            - name: MONGOPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopassword
                  key: MONGOPASSWORD